//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraaEdge.CRM.Repositoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SALES_ORDER_DATE { get; set; }
        public string Company { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> PLANNED { get; set; }
        public Nullable<double> COST { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
    }
}
